/* This file is automatically generated by CMake.  Do not modify by hand. */

#ifdef NETSNMP_TRANSPORT_AAL5PVC_DOMAIN
netsnmp_aal5pvc_ctor();
#endif
#ifdef NETSNMP_TRANSPORT_ALIAS_DOMAIN
netsnmp_alias_ctor();
#endif
#ifdef NETSNMP_TRANSPORT_CALLBACK_DOMAIN
//netsnmp_callback_ctor();
#endif
#ifdef NETSNMP_TRANSPORT_DTLSUDP_DOMAIN
netsnmp_dtlsudp_ctor();
#endif
#ifdef NETSNMP_TRANSPORT_IPV4BASE_DOMAIN
//netsnmp_ipv4base_ctor();
#endif
#ifdef NETSNMP_TRANSPORT_IPX_DOMAIN
netsnmp_ipx_ctor();
#endif
#ifdef NETSNMP_TRANSPORT_SSH_DOMAIN
netsnmp_ssh_ctor();
#endif
#ifdef NETSNMP_TRANSPORT_STD_DOMAIN
netsnmp_std_ctor();
#endif
#ifdef NETSNMP_TRANSPORT_TCP_DOMAIN
netsnmp_tcp_ctor();
#endif
#ifdef NETSNMP_TRANSPORT_TCPIPV6_DOMAIN
netsnmp_tcpipv6_ctor();
#endif
#ifdef NETSNMP_TRANSPORT_TLSBASE_DOMAIN
netsnmp_tlsbase_ctor();
#endif
#ifdef NETSNMP_TRANSPORT_TLSTCP_DOMAIN
netsnmp_tlstcp_ctor();
#endif
#ifdef NETSNMP_TRANSPORT_UDP_DOMAIN
netsnmp_udp_base_ctor();
netsnmp_udp_ctor();
#endif
#ifdef NETSNMP_TRANSPORT_UDPIPV6_DOMAIN
netsnmp_udpipv6_ctor();
#endif
#ifdef NETSNMP_TRANSPORT_UDPSHARED_DOMAIN
netsnmp_udpshared_ctor();
#endif
#ifdef NETSNMP_TRANSPORT_UNIX_DOMAIN
netsnmp_unix_ctor();
#endif